In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df =pd.read_csv("/Users/ahsan/Desktop/MyWork/airbnb_price_prediction/data/listings.csv")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14187 entries, 0 to 14186
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            14187 non-null  int64
 1   listing_url                                   14187 non-null  object
 2   scrape_id                                     14187 non-null  int64
 3   last_scraped                                  14187 non-null  object
 4   source                                        14187 non-null  object
 5   name                                          14187 non-null  object
 6   description                                   13584 non-null  object
 7   neighborhood_overview                         6540 non-null   object
 8   picture_url                                   14187 non-null  object
 9   host_id                                       14187 non-null  int64
 10  host_url                                      14187 non-null  object
 11  host_name                                     14174 non-null  object
 12  host_since                                    14174 non-null  object
 13  host_location                                 11217 non-null  object
 14  host_about                                    7357 non-null   object
 15  host_response_time                            9213 non-null   object
 16  host_response_rate                            9213 non-null   object
 17  host_acceptance_rate                          9829 non-null   object
 18  host_is_superhost                             13976 non-null  object
 19  host_thumbnail_url                            14174 non-null  object
 20  host_picture_url                              14174 non-null  object
 21  host_neighbourhood                            5907 non-null   object
 22  host_listings_count                           14174 non-null  float64
 23  host_total_listings_count                     14174 non-null  float64
 24  host_verifications                            14174 non-null  object
 25  host_has_profile_pic                          14174 non-null  object
 26  host_identity_verified                        14174 non-null  object
 27  neighbourhood                                 6540 non-null   object
 28  neighbourhood_cleansed                        14187 non-null  object
 29  neighbourhood_group_cleansed                  14187 non-null  object
 30  latitude                                      14187 non-null  float64
 31  longitude                                     14187 non-null  float64
 32  property_type                                 14187 non-null  object
 33  room_type                                     14187 non-null  object
 34  accommodates                                  14187 non-null  int64
 35  bathrooms                                     9232 non-null   float64
 36  bathrooms_text                                14180 non-null  object
 37  bedrooms                                      12164 non-null  float64
 38  beds                                          9184 non-null   float64
 39  amenities                                     14187 non-null  object
 40  price                                         9183 non-null   object
 41  minimum_nights                                14187 non-null  int64
 42  maximum_nights                                14187 non-null  int64
 43  minimum_minimum_nights                        14187 non-null  int64
 44  maximum_minimum_nights                        14187 non-null  int64
 45  minimum_maximum_nights                        14187 non-null  int64
 46  maximum_maximum_nights                        14187 non-null  int64
 47  minimum_nights_avg_ntm                        14187 non-null  float64
 48  maximum_nights_avg_ntm                        14187 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              13240 non-null  object
 51  availability_30                               14187 non-null  int64
 52  availability_60                               14187 non-null  int64
 53  availability_90                               14187 non-null  int64
 54  availability_365                              14187 non-null  int64
 55  calendar_last_scraped                         14187 non-null  object
 56  number_of_reviews                             14187 non-null  int64
 57  number_of_reviews_ltm                         14187 non-null  int64
 58  number_of_reviews_l30d                        14187 non-null  int64
 59  availability_eoy                              14187 non-null  int64
 60  number_of_reviews_ly                          14187 non-null  int64
 61  estimated_occupancy_l365d                     14187 non-null  int64
 62  estimated_revenue_l365d                       9183 non-null   float64
 63  first_review                                  10838 non-null  object
 64  last_review                                   10838 non-null  object
 65  review_scores_rating                          10838 non-null  float64
 66  review_scores_accuracy                        10836 non-null  float64
 67  review_scores_cleanliness                     10838 non-null  float64
 68  review_scores_checkin                         10835 non-null  float64
 69  review_scores_communication                   10837 non-null  float64
 70  review_scores_location                        10835 non-null  float64
 71  review_scores_value                           10833 non-null  float64
 72  license                                       5492 non-null   object
 73  instant_bookable                              14187 non-null  object
 74  calculated_host_listings_count                14187 non-null  int64
 75  calculated_host_listings_count_entire_homes   14187 non-null  int64
 76  calculated_host_listings_count_private_rooms  14187 non-null  int64
 77  calculated_host_listings_count_shared_rooms   14187 non-null  int64
 78  reviews_per_month                             10838 non-null  float64
dtypes: float64(19), int64(24), object(36)
memory usage: 8.6+ MB

In [8]:
cols_to_keep = [
    'price', 'accommodates', 'bedrooms', 'bathrooms_text',
    'room_type', 'property_type', 'minimum_nights',
    'availability_365', 'number_of_reviews',
    'review_scores_rating',
    'latitude', 'longitude',
    'neighbourhood_cleansed'
]

df_filtered = df[cols_to_keep].copy()

In [9]:
df_filtered.head()

,price,accommodates,bedrooms,bathrooms_text,room_type,property_type,minimum_nights,availability_365,number_of_reviews,review_scores_rating,latitude,longitude,neighbourhood_cleansed
0,$105.00,2,1.0,1 bath,Entire home/apt,Entire rental unit,63,250,149,4.63,52.53471,13.41810,Prenzlauer Berg Südwest
1,$135.00,7,4.0,2.5 baths,Entire home/apt,Entire rental unit,6,193,7,5.00,52.53269,13.41805,Prenzlauer Berg Südwest
2,$75.00,1,0.0,1 bath,Entire home/apt,Entire rental unit,150,262,26,4.68,52.54813,13.40366,Prenzlauer Berg Nordwest
3,NaN,4,1.0,1 bath,Entire home/apt,Entire condo,93,0,48,4.72,52.50312,13.43508,nördliche Luisenstadt
4,$28.00,2,0.0,1 bath,Entire home/apt,Entire rental unit,92,111,298,4.77,52.49419,13.42166,Reuterstraße

In [10]:
df_filtered.isnull().sum()

price                     5004
accommodates                 0
bedrooms                  2023
bathrooms_text               7
room_type                    0
property_type                0
minimum_nights               0
availability_365             0
number_of_reviews            0
review_scores_rating      3349
latitude                     0
longitude                    0
neighbourhood_cleansed       0
dtype: int64

In [11]:
df_filtered=df_filtered.dropna()

In [12]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7097 entries, 0 to 14105
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   price                   7097 non-null   object
 1   accommodates            7097 non-null   int64
 2   bedrooms                7097 non-null   float64
 3   bathrooms_text          7097 non-null   object
 4   room_type               7097 non-null   object
 5   property_type           7097 non-null   object
 6   minimum_nights          7097 non-null   int64
 7   availability_365        7097 non-null   int64
 8   number_of_reviews       7097 non-null   int64
 9   review_scores_rating    7097 non-null   float64
 10  latitude                7097 non-null   float64
 11  longitude               7097 non-null   float64
 12  neighbourhood_cleansed  7097 non-null   object
dtypes: float64(4), int64(4), object(5)
memory usage: 776.2+ KB

In [13]:
df_filtered.head()

,price,accommodates,bedrooms,bathrooms_text,room_type,property_type,minimum_nights,availability_365,number_of_reviews,review_scores_rating,latitude,longitude,neighbourhood_cleansed
0,$105.00,2,1.0,1 bath,Entire home/apt,Entire rental unit,63,250,149,4.63,52.53471,13.41810,Prenzlauer Berg Südwest
1,$135.00,7,4.0,2.5 baths,Entire home/apt,Entire rental unit,6,193,7,5.00,52.53269,13.41805,Prenzlauer Berg Südwest
2,$75.00,1,0.0,1 bath,Entire home/apt,Entire rental unit,150,262,26,4.68,52.54813,13.40366,Prenzlauer Berg Nordwest
4,$28.00,2,0.0,1 bath,Entire home/apt,Entire rental unit,92,111,298,4.77,52.49419,13.42166,Reuterstraße
6,$53.00,2,2.0,1 bath,Entire home/apt,Entire rental unit,93,52,182,4.70,52.53408,13.38871,Brunnenstr. Süd

In [14]:
df_filtered["price"] = (
    df_filtered["price"]
    .replace('[\$,]', '', regex=True)
    .astype(float)
)

In [15]:
df_filtered["price"].describe()

count     7097.000000
mean       180.790334
std       1239.082896
min          5.000000
25%         74.000000
50%        113.000000
75%        173.000000
max      50000.000000
Name: price, dtype: float64

In [16]:
df_filtered = df_filtered[df_filtered["price"] < 1000]

In [17]:
df_filtered["price"].describe()

count    7072.000000
mean      137.604072
std        95.260770
min         5.000000
25%        73.000000
50%       113.000000
75%       172.000000
max       992.000000
Name: price, dtype: float64

In [18]:
df_filtered.head()

,price,accommodates,bedrooms,bathrooms_text,room_type,property_type,minimum_nights,availability_365,number_of_reviews,review_scores_rating,latitude,longitude,neighbourhood_cleansed
0,105.0,2,1.0,1 bath,Entire home/apt,Entire rental unit,63,250,149,4.63,52.53471,13.41810,Prenzlauer Berg Südwest
1,135.0,7,4.0,2.5 baths,Entire home/apt,Entire rental unit,6,193,7,5.00,52.53269,13.41805,Prenzlauer Berg Südwest
2,75.0,1,0.0,1 bath,Entire home/apt,Entire rental unit,150,262,26,4.68,52.54813,13.40366,Prenzlauer Berg Nordwest
4,28.0,2,0.0,1 bath,Entire home/apt,Entire rental unit,92,111,298,4.77,52.49419,13.42166,Reuterstraße
6,53.0,2,2.0,1 bath,Entire home/apt,Entire rental unit,93,52,182,4.70,52.53408,13.38871,Brunnenstr. Süd

In [19]:
def parse_bathroom_text(text):
    if pd.isna(text):
        return np.nan
    text = text.lower()
    if "half-bath" in text:
        return 0.5
    try:
        # Extract numeric part for cases like "2 baths", "2.5 shared baths"
        return float(text.split()[0])
    except:
        return np.nan

In [20]:
df_filtered["bathrooms"] = df_filtered["bathrooms_text"].apply(parse_bathroom_text)

In [21]:
df_filtered.head()

,price,accommodates,bedrooms,bathrooms_text,room_type,property_type,minimum_nights,availability_365,number_of_reviews,review_scores_rating,latitude,longitude,neighbourhood_cleansed,bathrooms
0,105.0,2,1.0,1 bath,Entire home/apt,Entire rental unit,63,250,149,4.63,52.53471,13.41810,Prenzlauer Berg Südwest,1.0
1,135.0,7,4.0,2.5 baths,Entire home/apt,Entire rental unit,6,193,7,5.00,52.53269,13.41805,Prenzlauer Berg Südwest,2.5
2,75.0,1,0.0,1 bath,Entire home/apt,Entire rental unit,150,262,26,4.68,52.54813,13.40366,Prenzlauer Berg Nordwest,1.0
4,28.0,2,0.0,1 bath,Entire home/apt,Entire rental unit,92,111,298,4.77,52.49419,13.42166,Reuterstraße,1.0
6,53.0,2,2.0,1 bath,Entire home/apt,Entire rental unit,93,52,182,4.70,52.53408,13.38871,Brunnenstr. Süd,1.0

In [22]:
df_filtered["bathrooms"].describe()

count    7072.000000
mean        1.154624
std         0.456055
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         8.500000
Name: bathrooms, dtype: float64

In [23]:
df_filtered["bedrooms"] = df_filtered["bedrooms"].replace(0, 1)

In [24]:
df_filtered.head()

,price,accommodates,bedrooms,bathrooms_text,room_type,property_type,minimum_nights,availability_365,number_of_reviews,review_scores_rating,latitude,longitude,neighbourhood_cleansed,bathrooms
0,105.0,2,1.0,1 bath,Entire home/apt,Entire rental unit,63,250,149,4.63,52.53471,13.41810,Prenzlauer Berg Südwest,1.0
1,135.0,7,4.0,2.5 baths,Entire home/apt,Entire rental unit,6,193,7,5.00,52.53269,13.41805,Prenzlauer Berg Südwest,2.5
2,75.0,1,1.0,1 bath,Entire home/apt,Entire rental unit,150,262,26,4.68,52.54813,13.40366,Prenzlauer Berg Nordwest,1.0
4,28.0,2,1.0,1 bath,Entire home/apt,Entire rental unit,92,111,298,4.77,52.49419,13.42166,Reuterstraße,1.0
6,53.0,2,2.0,1 bath,Entire home/apt,Entire rental unit,93,52,182,4.70,52.53408,13.38871,Brunnenstr. Süd,1.0

In [25]:
df_filtered = pd.get_dummies(df_filtered, columns=['room_type'], drop_first=True)

In [26]:
df_filtered.head()

,price,accommodates,bedrooms,bathrooms_text,property_type,minimum_nights,availability_365,number_of_reviews,review_scores_rating,latitude,longitude,neighbourhood_cleansed,bathrooms,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,105.0,2,1.0,1 bath,Entire rental unit,63,250,149,4.63,52.53471,13.41810,Prenzlauer Berg Südwest,1.0,False,False,False
1,135.0,7,4.0,2.5 baths,Entire rental unit,6,193,7,5.00,52.53269,13.41805,Prenzlauer Berg Südwest,2.5,False,False,False
2,75.0,1,1.0,1 bath,Entire rental unit,150,262,26,4.68,52.54813,13.40366,Prenzlauer Berg Nordwest,1.0,False,False,False
4,28.0,2,1.0,1 bath,Entire rental unit,92,111,298,4.77,52.49419,13.42166,Reuterstraße,1.0,False,False,False
6,53.0,2,2.0,1 bath,Entire rental unit,93,52,182,4.70,52.53408,13.38871,Brunnenstr. Süd,1.0,False,False,False

In [27]:
top_neighbourhoods = df_filtered["neighbourhood_cleansed"].value_counts().nlargest(10).index

In [28]:
df_filtered["neighbourhood_cleansed"] = df_filtered["neighbourhood_cleansed"].apply(
    lambda x: x if x in top_neighbourhoods else "Other")

In [29]:
df_filtered = pd.get_dummies(df_filtered, columns=["neighbourhood_cleansed"], drop_first=True)

In [30]:
top_property_types = df_filtered['property_type'].value_counts().nlargest(10).index

In [31]:
df_filtered['property_type'] = df_filtered['property_type'].apply(lambda x: x if x in top_property_types else 'Other')

In [32]:
df_filtered = pd.get_dummies(df_filtered, columns=['property_type'], drop_first=True)

In [33]:
for col in df_filtered.select_dtypes(include='bool').columns:
    df_filtered[col] = df_filtered[col].astype(int)

In [35]:
berlin_center = (52.5200, 13.4050)  # latitude, longitude

In [36]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in kilometers
    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)
    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)

    a = np.sin(delta_phi / 2) ** 2 + \
        np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda / 2) ** 2

    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    return R * c

In [37]:
df_filtered['distance_to_center'] = df_filtered.apply(
    lambda row: haversine(row['latitude'], row['longitude'], berlin_center[0], berlin_center[1]),
    axis=1
)

In [38]:
df_filtered['distance_to_center'].describe()

count    7072.000000
mean        5.137638
std         3.800150
min         0.134921
25%         2.789248
50%         4.132775
75%         6.360012
max        25.455030
Name: distance_to_center, dtype: float64

In [39]:
df_filtered.drop(columns=[
    'bathrooms_text', 
    'latitude',
    'longitude'
], inplace=True)

In [40]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7072 entries, 0 to 14105
Data columns (total 32 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   price                                            7072 non-null   float64
 1   accommodates                                     7072 non-null   int64
 2   bedrooms                                         7072 non-null   float64
 3   minimum_nights                                   7072 non-null   int64
 4   availability_365                                 7072 non-null   int64
 5   number_of_reviews                                7072 non-null   int64
 6   review_scores_rating                             7072 non-null   float64
 7   bathrooms                                        7072 non-null   float64
 8   room_type_Hotel room                             7072 non-null   int64
 9   room_type_Private room                           7072 non-null   int64
 10  room_type_Shared room                            7072 non-null   int64
 11  neighbourhood_cleansed_Brunnenstr. Süd           7072 non-null   int64
 12  neighbourhood_cleansed_Frankfurter Allee Süd FK  7072 non-null   int64
 13  neighbourhood_cleansed_Karl-Marx-Allee-Süd       7072 non-null   int64
 14  neighbourhood_cleansed_Other                     7072 non-null   int64
 15  neighbourhood_cleansed_Prenzlauer Berg Süd       7072 non-null   int64
 16  neighbourhood_cleansed_Prenzlauer Berg Südwest   7072 non-null   int64
 17  neighbourhood_cleansed_Reuterstraße              7072 non-null   int64
 18  neighbourhood_cleansed_Schöneberg-Nord           7072 non-null   int64
 19  neighbourhood_cleansed_Tempelhofer Vorstadt      7072 non-null   int64
 20  neighbourhood_cleansed_südliche Luisenstadt      7072 non-null   int64
 21  property_type_Entire home                        7072 non-null   int64
 22  property_type_Entire loft                        7072 non-null   int64
 23  property_type_Entire rental unit                 7072 non-null   int64
 24  property_type_Entire serviced apartment          7072 non-null   int64
 25  property_type_Other                              7072 non-null   int64
 26  property_type_Private room in condo              7072 non-null   int64
 27  property_type_Private room in home               7072 non-null   int64
 28  property_type_Private room in hostel             7072 non-null   int64
 29  property_type_Private room in rental unit        7072 non-null   int64
 30  property_type_Room in hotel                      7072 non-null   int64
 31  distance_to_center                               7072 non-null   float64
dtypes: float64(5), int64(27)
memory usage: 1.8 MB

In [41]:
df_filtered.to_csv("../data/clean_airbnb_data.csv", index=False)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14187 entries, 0 to 14186
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            14187 non-null  int64
 1   listing_url                                   14187 non-null  object
 2   scrape_id                                     14187 non-null  int64
 3   last_scraped                                  14187 non-null  object
 4   source                                        14187 non-null  object
 5   name                                          14187 non-null  object
 6   description                                   13584 non-null  object
 7   neighborhood_overview                         6540 non-null   object
 8   picture_url                                   14187 non-null  object
 9   host_id                                       14187 non-null  int64
 10  host_url                                      14187 non-null  object
 11  host_name                                     14174 non-null  object
 12  host_since                                    14174 non-null  object
 13  host_location                                 11217 non-null  object
 14  host_about                                    7357 non-null   object
 15  host_response_time                            9213 non-null   object
 16  host_response_rate                            9213 non-null   object
 17  host_acceptance_rate                          9829 non-null   object
 18  host_is_superhost                             13976 non-null  object
 19  host_thumbnail_url                            14174 non-null  object
 20  host_picture_url                              14174 non-null  object
 21  host_neighbourhood                            5907 non-null   object
 22  host_listings_count                           14174 non-null  float64
 23  host_total_listings_count                     14174 non-null  float64
 24  host_verifications                            14174 non-null  object
 25  host_has_profile_pic                          14174 non-null  object
 26  host_identity_verified                        14174 non-null  object
 27  neighbourhood                                 6540 non-null   object
 28  neighbourhood_cleansed                        14187 non-null  object
 29  neighbourhood_group_cleansed                  14187 non-null  object
 30  latitude                                      14187 non-null  float64
 31  longitude                                     14187 non-null  float64
 32  property_type                                 14187 non-null  object
 33  room_type                                     14187 non-null  object
 34  accommodates                                  14187 non-null  int64
 35  bathrooms                                     9232 non-null   float64
 36  bathrooms_text                                14180 non-null  object
 37  bedrooms                                      12164 non-null  float64
 38  beds                                          9184 non-null   float64
 39  amenities                                     14187 non-null  object
 40  price                                         9183 non-null   object
 41  minimum_nights                                14187 non-null  int64
 42  maximum_nights                                14187 non-null  int64
 43  minimum_minimum_nights                        14187 non-null  int64
 44  maximum_minimum_nights                        14187 non-null  int64
 45  minimum_maximum_nights                        14187 non-null  int64
 46  maximum_maximum_nights                        14187 non-null  int64
 47  minimum_nights_avg_ntm                        14187 non-null  float64
 48  maximum_nights_avg_ntm                        14187 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              13240 non-null  object
 51  availability_30                               14187 non-null  int64
 52  availability_60                               14187 non-null  int64
 53  availability_90                               14187 non-null  int64
 54  availability_365                              14187 non-null  int64
 55  calendar_last_scraped                         14187 non-null  object
 56  number_of_reviews                             14187 non-null  int64
 57  number_of_reviews_ltm                         14187 non-null  int64
 58  number_of_reviews_l30d                        14187 non-null  int64
 59  availability_eoy                              14187 non-null  int64
 60  number_of_reviews_ly                          14187 non-null  int64
 61  estimated_occupancy_l365d                     14187 non-null  int64
 62  estimated_revenue_l365d                       9183 non-null   float64
 63  first_review                                  10838 non-null  object
 64  last_review                                   10838 non-null  object
 65  review_scores_rating                          10838 non-null  float64
 66  review_scores_accuracy                        10836 non-null  float64
 67  review_scores_cleanliness                     10838 non-null  float64
 68  review_scores_checkin                         10835 non-null  float64
 69  review_scores_communication                   10837 non-null  float64
 70  review_scores_location                        10835 non-null  float64
 71  review_scores_value                           10833 non-null  float64
 72  license                                       5492 non-null   object
 73  instant_bookable                              14187 non-null  object
 74  calculated_host_listings_count                14187 non-null  int64
 75  calculated_host_listings_count_entire_homes   14187 non-null  int64
 76  calculated_host_listings_count_private_rooms  14187 non-null  int64
 77  calculated_host_listings_count_shared_rooms   14187 non-null  int64
 78  reviews_per_month                             10838 non-null  float64
dtypes: float64(19), int64(24), object(36)
memory usage: 8.6+ MB

In [22]:
df.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [30]:
# Convert to float if not already
df.loc[:, "price"] = df["price"].replace(r'[\$,]', '', regex=True).astype(float)

# Remove listings with price above $1000
df = df[df["price"] <= 1000].copy()

In [34]:
# Convert price
df.loc[:, "price"] = df["price"].replace(r'[\$,]', '', regex=True).astype(float)

# Calculate IQR bounds
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1

# Define outlier limits
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter data
df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)].copy()

df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3176,https://www.airbnb.com/rooms/3176,20250620182343,2025-06-21,city scrape,Fabulous Flat in great Location,This beautiful first floor apartment is situa...,The neighbourhood is famous for its variety of...,https://a0.muscache.com/pictures/airflow/Hosti...,3718,...,4.70,4.92,4.61,NaN,f,1,1,0,0,0.76
1,9991,https://www.airbnb.com/rooms/9991,20250620182343,2025-06-21,city scrape,Geourgeous flat - outstanding views,4 bedroom with very large windows and outstand...,Prenzlauer Berg is an amazing neighbourhood wh...,https://a0.muscache.com/pictures/42799131/59c8...,33852,...,5.00,4.86,4.86,03/Z/RA/003410-18,f,1,1,0,0,0.06
2,14325,https://www.airbnb.com/rooms/14325,20250620182343,2025-06-21,city scrape,Studio Apartment in Prenzlauer Berg,The apartment is located on the upper second f...,NaN,https://a0.muscache.com/pictures/508703/24988a...,55531,...,4.85,4.60,4.45,NaN,f,4,4,0,0,0.14
4,17904,https://www.airbnb.com/rooms/17904,20250620182343,2025-06-21,city scrape,Beautiful Kreuzberg studio - 3 months minimum,"- apt is available starting September 1, 2024<...","The apartment is located in Kreuzberg, which i...",https://a0.muscache.com/pictures/d9a6f8be-54b9...,68997,...,4.92,4.88,4.65,NaN,f,1,1,0,0,1.60
6,22438,https://www.airbnb.com/rooms/22438,20250620182343,2025-06-21,city scrape,WOHNUNG IN BERLIN ★ MITTE,Free Internet and phone included.<br /><br />A...,"They are very nice, nice and independent.",https://a0.muscache.com/pictures/miso/Hosting-...,86159,...,4.73,4.63,4.68,NaN,f,1,1,0,0,1.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14182,1446408006383528333,https://www.airbnb.com/rooms/1446408006383528333,20250620182343,2025-06-20,city scrape,cozy room,It is a room with lots of light and you look o...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,420514457,...,NaN,NaN,NaN,08/Z/AZ/010492-21,f,2,0,2,0,0.00
14183,1446861918532076953,https://www.airbnb.com/rooms/1446861918532076953,20250620182343,2025-06-20,city scrape,Beautiful 1-Bedroom Apartment in Wedding,This stunning furnished one bedroom apartment ...,"Wedding is a lively and diverse neighborhood, ...",https://a0.muscache.com/pictures/prohost-api/H...,595670462,...,NaN,NaN,NaN,NaN,f,69,69,0,0,0.00
14184,1446862242596527946,https://www.airbnb.com/rooms/1446862242596527946,20250620182343,2025-06-20,city scrape,Stunning Studio in Wedding,This stunning furnished studio apartment featu...,"Wedding is a lively and diverse neighborhood, ...",https://a0.muscache.com/pictures/prohost-api/H...,595670462,...,NaN,NaN,NaN,NaN,f,69,69,0,0,0.00
14185,1446993798027111825,https://www.airbnb.com/rooms/1446993798027111825,20250620182343,2025-06-20,city scrape,Gemütliches Boot mit Seeblick,"Spend unforgettable hours on our charming, rom...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,569536089,...,NaN,NaN,NaN,First name and Last name: Taya P. <br/> Contac...,t,1,1,0,0,0.00
14186,1447175366954841201,https://www.airbnb.com/rooms/1447175366954841201,20250620182343,2025-06-21,city scrape,Apartment in the Heart of Mitte,Welcome to your summer oasis on Linienstraße —...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1099703,...,NaN,NaN,NaN,NaN,f,1,1,0,0,0.00